version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: server.Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
      - /home/node/data
    environment:
      DATA_PATH: /home/node/data/todos.json
